# Generated by Django 5.0.6 on 2024-08-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbvapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="sex",
            field=models.CharField(default="None", max_length=10),
        ),
    ]
